### ISSUE TITLE
Some currencies have other than 100 fractional units; and fractional units all are named "cents" in English

### ISSUE THREAD

**Issue by pavloslav** [Ballasi/num2words#17]
According to [Wiki](https://en.wikipedia.org/wiki/List_of_circulating_currencies), there are some currencies that are split in other number of fractions, like BHD (1000) or BND (10). Even Yuan is split into 10 Jiao, not 100. Sometimes currencies that have the same name have the different number of fractions, like Iraqi dinar (IQD) has 1000 Fils, and Serbian dinar (RSD) has 100 Para. There should be an additional argument in `to_currency` function.

Also, fractional units have their respective names.

This is a critical bug.

Historically, there were currencies with several fractional units, like the old [British Pound sterling](https://en.wikipedia.org/wiki/Pound_sterling#Pre-decimal) had 12 shillings, each shilling split into 20 pence before 1971. Thank God we should not support this.

**Comment by pavloslav** [comment]
Note: there are non-decimal currencies.
1 MRU ([Mauritanian ouguiya](https://en.wikipedia.org/wiki/Mauritanian_ouguiya)) is 5 khoums. Should 0.4 MRU be 2 khoums or 4 khoums?

**Comment by Ballasi** [comment]
I have added functionality for different currency cent names. However, after looking at the currencies that does not implement /100 subunits, it seems like it is very unlikely we are going to implement them in the future.

The only ones that are already included and does not use a /100 subunit is for instance yuan, which can be split in either /10 (jiao) or /100 (fen), and they are almost never used.
